### ISSUE TITLE
Suggestion for AppCenter: Keep old release information around in AppData

### ISSUE THREAD

**Issue by cassidyjames** [raibtoffoletto/litteris#15]
We use historical release information in AppCenter on the desktop and web; for example, if a user is on an older version, we will show information for all releases between their current version and the newest. We also display information about the last several releases on the AppCenter website so potential users can judge the release cadence and how frequently-updated your app is. 

If you replace old release information, we are unable to display it to users and they cannot see the historical data.

**Comment by raibtoffoletto** [comment]
Oh, thank you Cassidy, silly me was always erasing them. This detail escaped my attention when reading the docs. I realised that I forgot to change versions on the About window in the app as well, so will try to fix this with another point release.

If you are the one approving this current version, please hold on til I have the chance to correct and submit again! 😃
