### ISSUE TITLE
Screenshot URL in appdata returns 404

### ISSUE THREAD

**Issue by danirabbit** [raibtoffoletto/litteris#22]
It looks like there's a typo in your screenshot URLs. Instead of:

`https://github.com/raibtoffoletto/litteris/raw/master/data/com.github.raibtoffoletto.litteris.screenshot.png`

It should be
`https://raw.githubusercontent.com/raibtoffoletto/litteris/master/data/com.github.raibtoffoletto.litteris.screenshot.png`

**Comment by raibtoffoletto** [comment]
Oh, that address changed in the past 3 years, will fix it =D.
